// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIwFKcvUi9udasz_LUwj5gTKmrIjv3YPk',
    appId: '1:821787226502:android:47ff822c640dc4796a3c07',
    messagingSenderId: '821787226502',
    projectId: 'flask-test-1b99c',
    storageBucket: 'flask-test-1b99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OZdM9l1Umspi_ozUbjOwuMPxEZ_Hx1I',
    appId: '1:821787226502:ios:ff239f8f20b5e8356a3c07',
    messagingSenderId: '821787226502',
    projectId: 'flask-test-1b99c',
    storageBucket: 'flask-test-1b99c.firebasestorage.app',
    androidClientId: '821787226502-8fjeb2s7kfj2eo8u2qgvcstlai3q35ne.apps.googleusercontent.com',
    iosClientId: '821787226502-165kof6l38msqv781q8p0cthagqo76nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.resturantApp',
  );
}
